name: Databricks DAB Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  CD:
    name: Databricks DAB Deploy
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: lab
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      # --- DATA CONTRACT PRE-DEPLOY CHECK ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Install Data Contract CLI
        run: pip install datacontract-cli

      - name: Final Contract Validation
        run: |
          # Ensuring the contract is valid before it becomes 'Production'
          datacontract lint resources/datacontract.yml
      # ---------------------------------------

      - name: setup databricks cli
        uses: databricks/setup-cli@main

      - name: DAB Validation
        env:
          DATABRICKS_HOST: ${{ vars.DAB_DEPLOY }}
          DATABRICKS_TOKEN: ${{ secrets.DAB_DEPLOY }}
        run: |
          cd ${{ github.workspace }}/demo
          databricks bundle validate -p lab -t lab

      - name: DAB Deploy
        env:
          DATABRICKS_HOST: ${{ vars.DAB_DEPLOY }}
          DATABRICKS_TOKEN: ${{ secrets.DAB_DEPLOY }}
        run: |
          cd ${{ github.workspace }}/bundles
          # Deploying the pipeline that enforces the contract
          databricks bundle deploy -p lab -t lab --force