name: Databricks DAB Deploy
on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  CD:
    name: Databricks DAB Deploy
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: lab
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Data Contract CLI
        run: pip install "datacontract-cli[databricks]"

      - name: Final Contract Validation
        env:
          DATACONTRACT_DATABRICKS_TOKEN: ${{ secrets.DAB_DEPLOY }}
          DATACONTRACT_DATABRICKS_HOST: ${{ vars.DAB_DEPLOY }}
        run: |
          datacontract lint contract/datacontract.yml
          datacontract test contract/datacontract.yml --server production

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
        with:
          version: 0.299.0

      - name: DAB Validation & Deploy
        env:
          DATABRICKS_HOST: ${{ vars.DAB_DEPLOY }}
          DATABRICKS_TOKEN: ${{ secrets.DAB_DEPLOY }}
        run: |
          cd bundles
          databricks bundle validate -t lab
          databricks bundle deploy -t lab --force